// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/aiservice.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_aiservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_aiservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // PCM 16kHz 16bit mono
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 会话标识
	IsEnd         bool                   `protobuf:"varint,3,opt,name=is_end,json=isEnd,proto3" json:"is_end,omitempty"`            // 是否为最后一个 chunk（用户说完）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_aiservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *AudioChunk) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AudioChunk) GetIsEnd() bool {
	if x != nil {
		return x.IsEnd
	}
	return false
}

type ASRResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                       // 识别文本（partial 或 final）
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"` // 是否是最终结果
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Pronunciation int32                  `protobuf:"varint,4,opt,name=pronunciation,proto3" json:"pronunciation,omitempty"` // 发音评分 0-100
	Fluency       int32                  `protobuf:"varint,5,opt,name=fluency,proto3" json:"fluency,omitempty"`             // 流利度评分 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASRResult) Reset() {
	*x = ASRResult{}
	mi := &file_proto_aiservice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASRResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASRResult) ProtoMessage() {}

func (x *ASRResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASRResult.ProtoReflect.Descriptor instead.
func (*ASRResult) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{3}
}

func (x *ASRResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ASRResult) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *ASRResult) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ASRResult) GetPronunciation() int32 {
	if x != nil {
		return x.Pronunciation
	}
	return 0
}

func (x *ASRResult) GetFluency() int32 {
	if x != nil {
		return x.Fluency
	}
	return 0
}

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`                                // 场景: interview / ordering / meeting
	UserMessage   string                 `protobuf:"bytes,3,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"` // 用户刚说的（ASR 最终结果）
	History       []*ChatMessage         `protobuf:"bytes,4,rep,name=history,proto3" json:"history,omitempty"`                            // 对话历史（服务端也可从 Redis 获取）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_proto_aiservice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{4}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ChatRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *ChatRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // user / assistant
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_aiservice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatResponse_Reply
	//	*ChatResponse_Correction
	//	*ChatResponse_Done
	//	*ChatResponse_TtsAudio
	//	*ChatResponse_Translation
	Payload       isChatResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_proto_aiservice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{6}
}

func (x *ChatResponse) GetPayload() isChatResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatResponse) GetReply() *ReplyChunk {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Reply); ok {
			return x.Reply
		}
	}
	return nil
}

func (x *ChatResponse) GetCorrection() *Correction {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Correction); ok {
			return x.Correction
		}
	}
	return nil
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Done); ok {
			return x.Done
		}
	}
	return false
}

func (x *ChatResponse) GetTtsAudio() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_TtsAudio); ok {
			return x.TtsAudio
		}
	}
	return nil
}

func (x *ChatResponse) GetTranslation() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Translation); ok {
			return x.Translation
		}
	}
	return ""
}

type isChatResponse_Payload interface {
	isChatResponse_Payload()
}

type ChatResponse_Reply struct {
	Reply *ReplyChunk `protobuf:"bytes,1,opt,name=reply,proto3,oneof"` // 对话回复（流式 chunk）
}

type ChatResponse_Correction struct {
	Correction *Correction `protobuf:"bytes,2,opt,name=correction,proto3,oneof"` // 纠错结果（在 reply 完成后统一发送）
}

type ChatResponse_Done struct {
	Done bool `protobuf:"varint,3,opt,name=done,proto3,oneof"` // 整个对话轮次结束
}

type ChatResponse_TtsAudio struct {
	TtsAudio []byte `protobuf:"bytes,4,opt,name=tts_audio,json=ttsAudio,proto3,oneof"` // TTS 语音片段（MP3 chunk）
}

type ChatResponse_Translation struct {
	Translation string `protobuf:"bytes,5,opt,name=translation,proto3,oneof"` // AI 回复的中文翻译
}

func (*ChatResponse_Reply) isChatResponse_Payload() {}

func (*ChatResponse_Correction) isChatResponse_Payload() {}

func (*ChatResponse_Done) isChatResponse_Payload() {}

func (*ChatResponse_TtsAudio) isChatResponse_Payload() {}

func (*ChatResponse_Translation) isChatResponse_Payload() {}

type ReplyChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                       // LLM 生成的回复片段
	IsFirst       bool                   `protobuf:"varint,2,opt,name=is_first,json=isFirst,proto3" json:"is_first,omitempty"` // 第一个 chunk（前端标记开始播放）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyChunk) Reset() {
	*x = ReplyChunk{}
	mi := &file_proto_aiservice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyChunk) ProtoMessage() {}

func (x *ReplyChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyChunk.ProtoReflect.Descriptor instead.
func (*ReplyChunk) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ReplyChunk) GetIsFirst() bool {
	if x != nil {
		return x.IsFirst
	}
	return false
}

type Correction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Original      string                 `protobuf:"bytes,1,opt,name=original,proto3" json:"original,omitempty"`                    // 用户原句
	Corrected     string                 `protobuf:"bytes,2,opt,name=corrected,proto3" json:"corrected,omitempty"`                  // 纠正后句子
	ErrorType     string                 `protobuf:"bytes,3,opt,name=error_type,json=errorType,proto3" json:"error_type,omitempty"` // grammar / vocabulary / pronunciation_hint
	Highlights    []*WordFix             `protobuf:"bytes,4,rep,name=highlights,proto3" json:"highlights,omitempty"`                // 逐词标记，用于前端高亮
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Correction) Reset() {
	*x = Correction{}
	mi := &file_proto_aiservice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Correction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correction) ProtoMessage() {}

func (x *Correction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correction.ProtoReflect.Descriptor instead.
func (*Correction) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{8}
}

func (x *Correction) GetOriginal() string {
	if x != nil {
		return x.Original
	}
	return ""
}

func (x *Correction) GetCorrected() string {
	if x != nil {
		return x.Corrected
	}
	return ""
}

func (x *Correction) GetErrorType() string {
	if x != nil {
		return x.ErrorType
	}
	return ""
}

func (x *Correction) GetHighlights() []*WordFix {
	if x != nil {
		return x.Highlights
	}
	return nil
}

type WordFix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartIdx      int32                  `protobuf:"varint,1,opt,name=start_idx,json=startIdx,proto3" json:"start_idx,omitempty"`               // 原句中该词的起始字符位置
	EndIdx        int32                  `protobuf:"varint,2,opt,name=end_idx,json=endIdx,proto3" json:"end_idx,omitempty"`                     // 结束位置
	Suggestion    string                 `protobuf:"bytes,3,opt,name=suggestion,proto3" json:"suggestion,omitempty"`                            // 修改建议
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`                                        // error category: grammar|tense|preposition|article|vocabulary|word_choice|expression
	ExplanationCn string                 `protobuf:"bytes,5,opt,name=explanation_cn,json=explanationCn,proto3" json:"explanation_cn,omitempty"` // 中文解释
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordFix) Reset() {
	*x = WordFix{}
	mi := &file_proto_aiservice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordFix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordFix) ProtoMessage() {}

func (x *WordFix) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordFix.ProtoReflect.Descriptor instead.
func (*WordFix) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{9}
}

func (x *WordFix) GetStartIdx() int32 {
	if x != nil {
		return x.StartIdx
	}
	return 0
}

func (x *WordFix) GetEndIdx() int32 {
	if x != nil {
		return x.EndIdx
	}
	return 0
}

func (x *WordFix) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *WordFix) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WordFix) GetExplanationCn() string {
	if x != nil {
		return x.ExplanationCn
	}
	return ""
}

type SynthesizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // 待合成的文本
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ChunkId       int32                  `protobuf:"varint,3,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"` // 文本片段序号（用于排序）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SynthesizeRequest) Reset() {
	*x = SynthesizeRequest{}
	mi := &file_proto_aiservice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SynthesizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SynthesizeRequest) ProtoMessage() {}

func (x *SynthesizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SynthesizeRequest.ProtoReflect.Descriptor instead.
func (*SynthesizeRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{10}
}

func (x *SynthesizeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SynthesizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SynthesizeRequest) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

type TTSAudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"` // 合成音频 PCM/WAV
	ChunkId       int32                  `protobuf:"varint,2,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	IsFinal       bool                   `protobuf:"varint,3,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TTSAudioChunk) Reset() {
	*x = TTSAudioChunk{}
	mi := &file_proto_aiservice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TTSAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TTSAudioChunk) ProtoMessage() {}

func (x *TTSAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TTSAudioChunk.ProtoReflect.Descriptor instead.
func (*TTSAudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{11}
}

func (x *TTSAudioChunk) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TTSAudioChunk) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *TTSAudioChunk) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

type EvaluateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,2,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`             // 用户原始音频
	ReferenceText string                 `protobuf:"bytes,3,opt,name=reference_text,json=referenceText,proto3" json:"reference_text,omitempty"` // 参考文本（用户说的话）
	Transcript    string                 `protobuf:"bytes,4,opt,name=transcript,proto3" json:"transcript,omitempty"`                            // ASR 转录结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_proto_aiservice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{12}
}

func (x *EvaluateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EvaluateRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *EvaluateRequest) GetReferenceText() string {
	if x != nil {
		return x.ReferenceText
	}
	return ""
}

func (x *EvaluateRequest) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallScore  float32                `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"` // 总分 0-100
	Accuracy      float32                `protobuf:"fixed32,2,opt,name=accuracy,proto3" json:"accuracy,omitempty"`                             // 准确度
	Fluency       float32                `protobuf:"fixed32,3,opt,name=fluency,proto3" json:"fluency,omitempty"`                               // 流利度
	Completeness  float32                `protobuf:"fixed32,4,opt,name=completeness,proto3" json:"completeness,omitempty"`                     // 完整度
	WordScores    []*WordScore           `protobuf:"bytes,5,rep,name=word_scores,json=wordScores,proto3" json:"word_scores,omitempty"`         // 逐词发音评分
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_proto_aiservice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{13}
}

func (x *EvaluateResponse) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *EvaluateResponse) GetAccuracy() float32 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *EvaluateResponse) GetFluency() float32 {
	if x != nil {
		return x.Fluency
	}
	return 0
}

func (x *EvaluateResponse) GetCompleteness() float32 {
	if x != nil {
		return x.Completeness
	}
	return 0
}

func (x *EvaluateResponse) GetWordScores() []*WordScore {
	if x != nil {
		return x.WordScores
	}
	return nil
}

type WordScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	PhonemeDetail string                 `protobuf:"bytes,3,opt,name=phoneme_detail,json=phonemeDetail,proto3" json:"phoneme_detail,omitempty"` // 音素细节（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordScore) Reset() {
	*x = WordScore{}
	mi := &file_proto_aiservice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordScore) ProtoMessage() {}

func (x *WordScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordScore.ProtoReflect.Descriptor instead.
func (*WordScore) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{14}
}

func (x *WordScore) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordScore) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *WordScore) GetPhonemeDetail() string {
	if x != nil {
		return x.PhonemeDetail
	}
	return ""
}

type ReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"`
	History       []*ChatMessage         `protobuf:"bytes,3,rep,name=history,proto3" json:"history,omitempty"`
	Corrections   []*Correction          `protobuf:"bytes,4,rep,name=corrections,proto3" json:"corrections,omitempty"` // 会话中所有纠错记录
	Evaluations   []*EvaluateResponse    `protobuf:"bytes,5,rep,name=evaluations,proto3" json:"evaluations,omitempty"` // 发音评测记录
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_proto_aiservice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{15}
}

func (x *ReportRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReportRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

func (x *ReportRequest) GetHistory() []*ChatMessage {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *ReportRequest) GetCorrections() []*Correction {
	if x != nil {
		return x.Corrections
	}
	return nil
}

func (x *ReportRequest) GetEvaluations() []*EvaluateResponse {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverallScore  float32                `protobuf:"fixed32,1,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"` // 综合分
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`                                 // 总结（Markdown 格式）
	WeakPoints    []*WeakPoint           `protobuf:"bytes,3,rep,name=weak_points,json=weakPoints,proto3" json:"weak_points,omitempty"`
	Suggestions   []string               `protobuf:"bytes,4,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_proto_aiservice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{16}
}

func (x *ReportResponse) GetOverallScore() float32 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *ReportResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReportResponse) GetWeakPoints() []*WeakPoint {
	if x != nil {
		return x.WeakPoints
	}
	return nil
}

func (x *ReportResponse) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type WeakPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // grammar / pronunciation / vocabulary / fluency
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Frequency     int32                  `protobuf:"varint,3,opt,name=frequency,proto3" json:"frequency,omitempty"` // 出现次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeakPoint) Reset() {
	*x = WeakPoint{}
	mi := &file_proto_aiservice_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeakPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeakPoint) ProtoMessage() {}

func (x *WeakPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aiservice_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeakPoint.ProtoReflect.Descriptor instead.
func (*WeakPoint) Descriptor() ([]byte, []int) {
	return file_proto_aiservice_proto_rawDescGZIP(), []int{17}
}

func (x *WeakPoint) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *WeakPoint) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *WeakPoint) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

var File_proto_aiservice_proto protoreflect.FileDescriptor

const file_proto_aiservice_proto_rawDesc = "" +
	"\n" +
	"\x15proto/aiservice.proto\x12\taiservice\"\x0f\n" +
	"\rHealthRequest\":\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\n" +
	"AudioChunk\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06is_end\x18\x03 \x01(\bR\x05isEnd\"\x99\x01\n" +
	"\tASRResult\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12$\n" +
	"\rpronunciation\x18\x04 \x01(\x05R\rpronunciation\x12\x18\n" +
	"\afluency\x18\x05 \x01(\x05R\afluency\"\x97\x01\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\x12!\n" +
	"\fuser_message\x18\x03 \x01(\tR\vuserMessage\x120\n" +
	"\ahistory\x18\x04 \x03(\v2\x16.aiservice.ChatMessageR\ahistory\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"\xda\x01\n" +
	"\fChatResponse\x12-\n" +
	"\x05reply\x18\x01 \x01(\v2\x15.aiservice.ReplyChunkH\x00R\x05reply\x127\n" +
	"\n" +
	"correction\x18\x02 \x01(\v2\x15.aiservice.CorrectionH\x00R\n" +
	"correction\x12\x14\n" +
	"\x04done\x18\x03 \x01(\bH\x00R\x04done\x12\x1d\n" +
	"\ttts_audio\x18\x04 \x01(\fH\x00R\bttsAudio\x12\"\n" +
	"\vtranslation\x18\x05 \x01(\tH\x00R\vtranslationB\t\n" +
	"\apayload\";\n" +
	"\n" +
	"ReplyChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_first\x18\x02 \x01(\bR\aisFirst\"\x99\x01\n" +
	"\n" +
	"Correction\x12\x1a\n" +
	"\boriginal\x18\x01 \x01(\tR\boriginal\x12\x1c\n" +
	"\tcorrected\x18\x02 \x01(\tR\tcorrected\x12\x1d\n" +
	"\n" +
	"error_type\x18\x03 \x01(\tR\terrorType\x122\n" +
	"\n" +
	"highlights\x18\x04 \x03(\v2\x12.aiservice.WordFixR\n" +
	"highlights\"\x9a\x01\n" +
	"\aWordFix\x12\x1b\n" +
	"\tstart_idx\x18\x01 \x01(\x05R\bstartIdx\x12\x17\n" +
	"\aend_idx\x18\x02 \x01(\x05R\x06endIdx\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x03 \x01(\tR\n" +
	"suggestion\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12%\n" +
	"\x0eexplanation_cn\x18\x05 \x01(\tR\rexplanationCn\"a\n" +
	"\x11SynthesizeRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x19\n" +
	"\bchunk_id\x18\x03 \x01(\x05R\achunkId\"d\n" +
	"\rTTSAudioChunk\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x19\n" +
	"\bchunk_id\x18\x02 \x01(\x05R\achunkId\x12\x19\n" +
	"\bis_final\x18\x03 \x01(\bR\aisFinal\"\x96\x01\n" +
	"\x0fEvaluateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x02 \x01(\fR\taudioData\x12%\n" +
	"\x0ereference_text\x18\x03 \x01(\tR\rreferenceText\x12\x1e\n" +
	"\n" +
	"transcript\x18\x04 \x01(\tR\n" +
	"transcript\"\xc8\x01\n" +
	"\x10EvaluateResponse\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x12\x1a\n" +
	"\baccuracy\x18\x02 \x01(\x02R\baccuracy\x12\x18\n" +
	"\afluency\x18\x03 \x01(\x02R\afluency\x12\"\n" +
	"\fcompleteness\x18\x04 \x01(\x02R\fcompleteness\x125\n" +
	"\vword_scores\x18\x05 \x03(\v2\x14.aiservice.WordScoreR\n" +
	"wordScores\"\\\n" +
	"\tWordScore\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12%\n" +
	"\x0ephoneme_detail\x18\x03 \x01(\tR\rphonemeDetail\"\xee\x01\n" +
	"\rReportRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\x120\n" +
	"\ahistory\x18\x03 \x03(\v2\x16.aiservice.ChatMessageR\ahistory\x127\n" +
	"\vcorrections\x18\x04 \x03(\v2\x15.aiservice.CorrectionR\vcorrections\x12=\n" +
	"\vevaluations\x18\x05 \x03(\v2\x1b.aiservice.EvaluateResponseR\vevaluations\"\xa8\x01\n" +
	"\x0eReportResponse\x12#\n" +
	"\roverall_score\x18\x01 \x01(\x02R\foverallScore\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\x125\n" +
	"\vweak_points\x18\x03 \x03(\v2\x14.aiservice.WeakPointR\n" +
	"weakPoints\x12 \n" +
	"\vsuggestions\x18\x04 \x03(\tR\vsuggestions\"]\n" +
	"\tWeakPoint\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x16\n" +
	"\x06detail\x18\x02 \x01(\tR\x06detail\x12\x1c\n" +
	"\tfrequency\x18\x03 \x01(\x05R\tfrequency2\x94\x03\n" +
	"\tAIService\x12<\n" +
	"\tStreamASR\x12\x15.aiservice.AudioChunk\x1a\x14.aiservice.ASRResult(\x010\x01\x129\n" +
	"\x04Chat\x12\x16.aiservice.ChatRequest\x1a\x17.aiservice.ChatResponse0\x01\x12C\n" +
	"\n" +
	"Synthesize\x12\x1c.aiservice.SynthesizeRequest\x1a\x15.aiservice.AudioChunk0\x01\x12C\n" +
	"\bEvaluate\x12\x1a.aiservice.EvaluateRequest\x1a\x1b.aiservice.EvaluateResponse\x12E\n" +
	"\x0eGenerateReport\x12\x18.aiservice.ReportRequest\x1a\x19.aiservice.ReportResponse\x12=\n" +
	"\x06Health\x12\x18.aiservice.HealthRequest\x1a\x19.aiservice.HealthResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_aiservice_proto_rawDescOnce sync.Once
	file_proto_aiservice_proto_rawDescData []byte
)

func file_proto_aiservice_proto_rawDescGZIP() []byte {
	file_proto_aiservice_proto_rawDescOnce.Do(func() {
		file_proto_aiservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aiservice_proto_rawDesc), len(file_proto_aiservice_proto_rawDesc)))
	})
	return file_proto_aiservice_proto_rawDescData
}

var file_proto_aiservice_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_aiservice_proto_goTypes = []any{
	(*HealthRequest)(nil),     // 0: aiservice.HealthRequest
	(*HealthResponse)(nil),    // 1: aiservice.HealthResponse
	(*AudioChunk)(nil),        // 2: aiservice.AudioChunk
	(*ASRResult)(nil),         // 3: aiservice.ASRResult
	(*ChatRequest)(nil),       // 4: aiservice.ChatRequest
	(*ChatMessage)(nil),       // 5: aiservice.ChatMessage
	(*ChatResponse)(nil),      // 6: aiservice.ChatResponse
	(*ReplyChunk)(nil),        // 7: aiservice.ReplyChunk
	(*Correction)(nil),        // 8: aiservice.Correction
	(*WordFix)(nil),           // 9: aiservice.WordFix
	(*SynthesizeRequest)(nil), // 10: aiservice.SynthesizeRequest
	(*TTSAudioChunk)(nil),     // 11: aiservice.TTSAudioChunk
	(*EvaluateRequest)(nil),   // 12: aiservice.EvaluateRequest
	(*EvaluateResponse)(nil),  // 13: aiservice.EvaluateResponse
	(*WordScore)(nil),         // 14: aiservice.WordScore
	(*ReportRequest)(nil),     // 15: aiservice.ReportRequest
	(*ReportResponse)(nil),    // 16: aiservice.ReportResponse
	(*WeakPoint)(nil),         // 17: aiservice.WeakPoint
}
var file_proto_aiservice_proto_depIdxs = []int32{
	5,  // 0: aiservice.ChatRequest.history:type_name -> aiservice.ChatMessage
	7,  // 1: aiservice.ChatResponse.reply:type_name -> aiservice.ReplyChunk
	8,  // 2: aiservice.ChatResponse.correction:type_name -> aiservice.Correction
	9,  // 3: aiservice.Correction.highlights:type_name -> aiservice.WordFix
	14, // 4: aiservice.EvaluateResponse.word_scores:type_name -> aiservice.WordScore
	5,  // 5: aiservice.ReportRequest.history:type_name -> aiservice.ChatMessage
	8,  // 6: aiservice.ReportRequest.corrections:type_name -> aiservice.Correction
	13, // 7: aiservice.ReportRequest.evaluations:type_name -> aiservice.EvaluateResponse
	17, // 8: aiservice.ReportResponse.weak_points:type_name -> aiservice.WeakPoint
	2,  // 9: aiservice.AIService.StreamASR:input_type -> aiservice.AudioChunk
	4,  // 10: aiservice.AIService.Chat:input_type -> aiservice.ChatRequest
	10, // 11: aiservice.AIService.Synthesize:input_type -> aiservice.SynthesizeRequest
	12, // 12: aiservice.AIService.Evaluate:input_type -> aiservice.EvaluateRequest
	15, // 13: aiservice.AIService.GenerateReport:input_type -> aiservice.ReportRequest
	0,  // 14: aiservice.AIService.Health:input_type -> aiservice.HealthRequest
	3,  // 15: aiservice.AIService.StreamASR:output_type -> aiservice.ASRResult
	6,  // 16: aiservice.AIService.Chat:output_type -> aiservice.ChatResponse
	2,  // 17: aiservice.AIService.Synthesize:output_type -> aiservice.AudioChunk
	13, // 18: aiservice.AIService.Evaluate:output_type -> aiservice.EvaluateResponse
	16, // 19: aiservice.AIService.GenerateReport:output_type -> aiservice.ReportResponse
	1,  // 20: aiservice.AIService.Health:output_type -> aiservice.HealthResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_aiservice_proto_init() }
func file_proto_aiservice_proto_init() {
	if File_proto_aiservice_proto != nil {
		return
	}
	file_proto_aiservice_proto_msgTypes[6].OneofWrappers = []any{
		(*ChatResponse_Reply)(nil),
		(*ChatResponse_Correction)(nil),
		(*ChatResponse_Done)(nil),
		(*ChatResponse_TtsAudio)(nil),
		(*ChatResponse_Translation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aiservice_proto_rawDesc), len(file_proto_aiservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_aiservice_proto_goTypes,
		DependencyIndexes: file_proto_aiservice_proto_depIdxs,
		MessageInfos:      file_proto_aiservice_proto_msgTypes,
	}.Build()
	File_proto_aiservice_proto = out.File
	file_proto_aiservice_proto_goTypes = nil
	file_proto_aiservice_proto_depIdxs = nil
}
