# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import aiservice_pb2 as aiservice__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aiservice_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub:
    """============================================
    AI 英语口语陪练 — Go ↔ Python gRPC 协议
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamASR = channel.stream_stream(
                '/aiservice.AIService/StreamASR',
                request_serializer=aiservice__pb2.AudioChunk.SerializeToString,
                response_deserializer=aiservice__pb2.ASRResult.FromString,
                _registered_method=True)
        self.Chat = channel.unary_stream(
                '/aiservice.AIService/Chat',
                request_serializer=aiservice__pb2.ChatRequest.SerializeToString,
                response_deserializer=aiservice__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.Synthesize = channel.unary_stream(
                '/aiservice.AIService/Synthesize',
                request_serializer=aiservice__pb2.SynthesizeRequest.SerializeToString,
                response_deserializer=aiservice__pb2.AudioChunk.FromString,
                _registered_method=True)
        self.Evaluate = channel.unary_unary(
                '/aiservice.AIService/Evaluate',
                request_serializer=aiservice__pb2.EvaluateRequest.SerializeToString,
                response_deserializer=aiservice__pb2.EvaluateResponse.FromString,
                _registered_method=True)
        self.GenerateReport = channel.unary_unary(
                '/aiservice.AIService/GenerateReport',
                request_serializer=aiservice__pb2.ReportRequest.SerializeToString,
                response_deserializer=aiservice__pb2.ReportResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/aiservice.AIService/Health',
                request_serializer=aiservice__pb2.HealthRequest.SerializeToString,
                response_deserializer=aiservice__pb2.HealthResponse.FromString,
                _registered_method=True)


class AIServiceServicer:
    """============================================
    AI 英语口语陪练 — Go ↔ Python gRPC 协议
    ============================================

    """

    def StreamASR(self, request_iterator, context):
        """流式 ASR：Go 推送音频流，Python 返回识别结果（partial + final）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """LLM 对话：Go 发送对话上下文，Python 流式返回对话回复 + 同步纠错
        一次 LLM 调用同时产出 reply 和 correction，避免两次推理
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Synthesize(self, request, context):
        """流式 TTS：Go 发送文本，Python 流式返回合成音频
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Evaluate(self, request, context):
        """发音评测（非流式，异步处理）：音频 + 参考文本 → 评分
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateReport(self, request, context):
        """课后报告生成：聚合对话历史 → 结构化报告
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamASR': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamASR,
                    request_deserializer=aiservice__pb2.AudioChunk.FromString,
                    response_serializer=aiservice__pb2.ASRResult.SerializeToString,
            ),
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=aiservice__pb2.ChatRequest.FromString,
                    response_serializer=aiservice__pb2.ChatResponse.SerializeToString,
            ),
            'Synthesize': grpc.unary_stream_rpc_method_handler(
                    servicer.Synthesize,
                    request_deserializer=aiservice__pb2.SynthesizeRequest.FromString,
                    response_serializer=aiservice__pb2.AudioChunk.SerializeToString,
            ),
            'Evaluate': grpc.unary_unary_rpc_method_handler(
                    servicer.Evaluate,
                    request_deserializer=aiservice__pb2.EvaluateRequest.FromString,
                    response_serializer=aiservice__pb2.EvaluateResponse.SerializeToString,
            ),
            'GenerateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateReport,
                    request_deserializer=aiservice__pb2.ReportRequest.FromString,
                    response_serializer=aiservice__pb2.ReportResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=aiservice__pb2.HealthRequest.FromString,
                    response_serializer=aiservice__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiservice.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiservice.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService:
    """============================================
    AI 英语口语陪练 — Go ↔ Python gRPC 协议
    ============================================

    """

    @staticmethod
    def StreamASR(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aiservice.AIService/StreamASR',
            aiservice__pb2.AudioChunk.SerializeToString,
            aiservice__pb2.ASRResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiservice.AIService/Chat',
            aiservice__pb2.ChatRequest.SerializeToString,
            aiservice__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Synthesize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aiservice.AIService/Synthesize',
            aiservice__pb2.SynthesizeRequest.SerializeToString,
            aiservice__pb2.AudioChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Evaluate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiservice.AIService/Evaluate',
            aiservice__pb2.EvaluateRequest.SerializeToString,
            aiservice__pb2.EvaluateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiservice.AIService/GenerateReport',
            aiservice__pb2.ReportRequest.SerializeToString,
            aiservice__pb2.ReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiservice.AIService/Health',
            aiservice__pb2.HealthRequest.SerializeToString,
            aiservice__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
